import { Permission } from "./enum/permission.enum";
import { Role } from "./enum/role.enum";

export const RolePermissions = {
    [Role.Admin]: [
        Permission.ViewProfile,
        Permission.UpdateProfile,
        Permission.ViewUser,
        Permission.ViewUsers,
        Permission.RemoveUser,
        Permission.UpdateUser,
        Permission.ViewProject,
        Permission.ViewProjects,
        Permission.CreateProject,
        Permission.UpdateProject,
        Permission.RemoveProject,
        Permission.SuperOwner,
        Permission.CreateTask,
        Permission.ViewTask,
        Permission.ViewTasks,
        Permission.RemoveTask,
        Permission.UpdateTask,
        Permission.CreateRole,
        Permission.ViewRole,
        Permission.ViewRoles,
        Permission.RemoveRole,
        Permission.UpdateRole,
    ],
    [Role.Client]: [
        Permission.ViewProfile,
        Permission.UpdateProfile,
        Permission.ViewProject,
        Permission.ViewTasks,

    ],
    [Role.Member]: [
        Permission.ViewProfile,
        Permission.UpdateProfile,
        Permission.ViewUser,
        Permission.ViewUsers,
        // Permission.ViewProject,
        Permission.ViewTasks,
        Permission.UpdateTask,
    ],
    [Role.ProjectManager]: [
        Permission.ViewProfile,
        Permission.UpdateProfile,
        Permission.ViewUser,
        Permission.ViewUsers,
        Permission.ViewProject,
        Permission.UpdateUser,
        Permission.CreateTask,
        Permission.ViewTasks,
        Permission.UpdateTask,
        Permission.RemoveTask,
    ],
    [Role.TeamLead]: [
        Permission.ViewProfile,
        Permission.UpdateProfile,
        Permission.ViewUser,
        Permission.ViewUsers,
        Permission.ViewProject,
        Permission.CreateTask,
        Permission.ViewTasks,
        Permission.UpdateTask,
    ],
}